name: marcovanthiel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009ee0'
    - '#b0dff5'
    - '#0000ff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.0625
  lightness: 0.9066482628695667
  saturation: 0
  rhythmicContrast: 0.11906255013309419
purpose: []
