name: marcovanthiel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5013974898029119
  lightness: 0.9066482628695667
  saturation: 0.2954675876535475
  rhythmicContrast: 0.11906255013309419
purpose: []
