name: Marco van Thiel
favicon: null
layout_spectrum: 0.76609
typography_spectrum: 0
title: 'Marco van Thiel, Projectmanager, interimmanager, change manager, ICT adviseur'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71312950-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060c'
    - '#5569b0'
    - '#50121f'
    - '#c5635a'
    - '#974338'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
