name: marcovanthiel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59152
title: 'Marco van Thiel, Projectmanager, interimmanager, change manager, ICT adviseur'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71312950-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060c'
    - '#5569b0'
    - '#50121f'
    - '#c5635a'
    - '#974338'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
